# Generated by Django 3.1 on 2020-10-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IG', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to='profiles/'),
        ),
    ]
