# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-22 15:17
from __future__ import unicode_literals

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('IG', '0006_auto_20201022_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_photo',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=pyuploadcare.dj.models.ImageField(null=True),
        ),
    ]
